language: node_js
node_js:
  - "0.10"
install:
  - sudo apt-get install npm
  - npm config set registry http://registry.npmjs.org/
  - npm install
script:
  - bash -x test/screenshot_script.sh
  - mocha --reporter=nyan test/unit-tests/basic-test.js
